### PR TITLE
Switch Espresso to python

### LINKED ISSUE #11: Espresso tutorial needs an update from tcl to python
Bascially the `spce.tcl` in https://github.com/votca/csg-tutorials/tree/master/spce/ibi_espresso needs to be converted to python.

### PR DESCRIPTION
**Pull request by fweik**
This should now work when https://github.com/espressomd/espresso/pull/2520 is merged. There is still the issue that the convention for the potential tables has changed:

This is not complete yet: The convention for the force tables changed, in the tcl version there was an implicit factor `1/r` (c.f. 5.1.1. of [the User's Guide](http://espressomd.org/wordpress/wp-content/uploads/2017/06/ESPResSo_3.3.1_UsersGuide.pdf)), which is no longer there in the python version. So probably the output of votca has to be adapted. It would also probably make sense to pack the tables together with the range into a xml or something so that it can be read automatically.

Also I changed the output format to h5md, which Espresso has native support for and which is also supported by votca. I now use MDAnalysis to read in the topology, if that external dependency should be avoided Espresso can read pdb files (but funny enough it can not read h5md files, which it can write).
The self-coded gro parser seemed brittle to me, but of course you can also put that back in.

Eventually fixes #11.

### CODE REVIEW

**Comment by junghans** [comment]
We need for https://github.com/espressomd/espresso/pull/2520 to make it into the fedora package!

**Comment by junghans** [comment]
This is part of espresso-4.0.2.

**Comment by junghans** [comment]
espresso-4.0.2 is part of F29 now.

**Comment by junghans** [comment]
Still:
```
     Start 109: spce_ibi_espresso
11/22 Test #109: spce_ibi_espresso ................Child terminated***Exception:   5.98 sec
For a more verbose log see: inverse.log
We are doing Method: ibi
[34;01mPrepare (dir step_000)[0m
Using initial guess from dist CG-CG.dist.tgt for CG-CG
[34;01m######################################################[0m
[34;01m# WARNING using this simulator is still experimental #[0m
[34;01m# If you find a problem report it under:             #[0m
[34;01m# https://github.com/votca/csg                       #[0m
[34;01m######################################################[0m
step 0 done
[34;01mDoing iteration 1 (dir step_001)[0m
Simulation with espresso
[34;01mReplace steps_per_int in 'spce.py' to be 500 and int_steps to be 1[0m
[31;01m###################################################################################################
#                                                                                                 #
# ERROR:                                                                                          #
# critical: 'python3 spce.py' failed                                                              #
# For details see the logfile /home/votca/votca/build/csg-tutorials/spce/ibi_espresso/inverse.log #
#                                                                                                 #
###################################################################################################[0m
```

**Comment by junghans** [comment]
Ok got it:
```
Running critical command 'python3 spce.py'
Traceback (most recent call last):
  File "spce.py", line 7, in <module>
    import MDAnalysis as mda
ModuleNotFoundError: No module named 'MDAnalysis'
```
however F29 doesn't have a python3 version of MDAnalysis (only python2), so we will have to wait for F30.

@fweik or is there are file format Espresso can read natively (with MDAnalysis)?

**Comment by junghans** [comment]
Now it fails at:
```
Running critical command 'python3 spce.py'
/usr/lib64/python3.7/site-packages/MDAnalysis/due.py:88: UserWarning: No module named 'duecredit'
  warnings.warn(str(err))
Program Information:
['BOND_ANGLE', 'BUCKINGHAM', 'COLLISION_DETECTION', 'ELECTROSTATICS', 'EXCLUSIONS', 'EXTERNAL_FORCES', 'FFTW', 'GAUSSIAN', 'GHOSTS_HAVE_BONDS', 'GSL', 'HERTZIAN', 'LANGEVIN_PER_PARTICLE', 'LATTICE', 'LB', 'LB_BOUNDARIES', 'LENNARD_JONES', 'LENNARD_JONES_GENERIC', 'LJCOS', 'LJCOS2', 'MASS', 'MORSE', 'NPT', 'P3M', 'PARTIAL_PERIODIC', 'SOFT_SPHERE', 'TABULATED']

number of particles:  2180
box size:  [40.31000137 40.31000137 40.31000137]
initial temperature:  0.0
warmup step 0
Running at temperature T=0.16
Traceback (most recent call last):
  File "spce.py", line 74, in <module>
    write_force=True, write_species=False, write_mass=True, write_ordered=False)
  File "/usr/lib64/python3.7/site-packages/openmpi/espressomd/io/writer/h5md.py", line 83, in __init__
    "ScriptInterface::Writer::H5mdScript")
  File "script_interface.pyx", line 29, in espressomd.script_interface.PScriptInterface.__init__
ValueError: Class 'ScriptInterface::Writer::H5mdScript' not found.
```

seems like Fedora's espresso misses h5md support.

**Comment by junghans** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2019-45e3407799

**Comment by junghans** [comment]
Ok with the update espresso package I got a step further, so no there is a problem when running `csg_stat`:
```
Running critical command 'csg_stat --nt 1 --options /home/junghans/votca/build/csg-tutorials/spce/ibi_espresso/settings.xml --top topol.xml --trj traj.h5 --begin 0 --first-frame 0'
begin to calculate distribution functions
# of bonded interactions: 0
# of non-bonded interactions: 1
WARNING: topology created from .gro file, masses and charges are wrong!
I have 2180 beads in 2180 molecules
Major version 1
Minor version 1
an error occurred:
Wrong version of H5MD file.: iostream error
```

@jkrajniak do you know something about this error?

**Comment by jkrajniak** [comment]
Espresso set version of h5md to 1.1; I made a small bugfix to allow <=1.1 versions of h5md.
https://github.com/votca/csg/pull/384

**Comment by junghans** [comment]
Ok, a bit further:
```
Missing particle group in topology. Please set `h5md_particle_group` tag with `name` attribute set to the particle group.: iostream error
```

**Comment by junghans** [comment]
> Ok, a bit further:
> 
> ```
> Missing particle group in topology. Please set `h5md_particle_group` tag with `name` attribute set to the particle group.: iostream error
> ```

Ok, I fixed that by adding a `h5md_particle_group` tag to `topol.xml`, but now it segfaults:
```
csg_stat --nt 1 --options settings.xml --top topol.xml --trj traj.h5 --begin 0 --first-frame 0
begin to calculate distribution functions
# of bonded interactions: 0
# of non-bonded interactions: 1
WARNING: topology created from .gro file, masses and charges are wrong!
I have 2180 beads in 2180 molecules
H5MD: static box
H5MD: Found box 40.31 x 40.31 x 40.31
H5MD: has /force
H5MD: has /velocity
H5MD: has /id group
Reading frame: 0
Segmentation fault (core dumped)
```

Input files here: [h5md_input.zip](https://github.com/votca/csg-tutorials/files/3378594/h5md_input.zip)

**Comment by junghans** [comment]
```
      Start 111: regression_spce_ibi_espresso
11/22 Test #111: regression_spce_ibi_espresso ................   Passed   12.47 sec
```

I think this is finally ready to be merged!

Thanks @jkrajniak @fweik

**Pull request merged**
