### PR TITLE
fix propane/imc and add propane/imc-ibiintra

### PR DESCRIPTION
**Pull request by marvinbernhardt**

### CODE REVIEW

**Comment by junghans** [comment]
Can we keep the file name `settings.xml` as otherwise CMake won't pick it up as a test.

**Comment by junghans** [comment]
In other case we made a `pre` directory e.g. ./urea-water/cibi/pre`

**Comment by marvinbernhardt** [comment]
> In other case we made a `pre` directory e.g. ./urea-water/cibi/pre`

will do that

**Comment by marvinbernhardt** [comment]
I think the checks will pass when https://github.com/votca/csg/pull/696 is merged.

**Comment by marvinbernhardt** [comment]
I'm trying to reproduce this at home. Both with my local build and in the `fedora:gmx2019_d` docker container. In both cases it is two different regression tests that fail

- regression_methanol_imc
- regression_propane_imc-ibiintra

and both fail due to low sampled IMC matrix which leads to noisy potentials and `gmx mdrun` crashing.

What am I missing? Why is the pre-run (IBI) failing in the CI?

**Comment by junghans** [comment]
The IMC test were always a bit brittle, we might need to increase the number of steps for the tests (in CMake). I still wondering why the CI passed though.

**Comment by junghans** [comment]
Replaced by https://github.com/votca/votca/pull/821

**Pull request closed without merging**
