### PR TITLE
spce/ibi_espresso: update for espresso v4.1.2

### PR DESCRIPTION
**Pull request by junghans**
@jngrad: please review

### CODE REVIEW

**Comment by junghans** [comment]
@jkrajniak with this fix, I am seeing:
```
Found H5MD version: 4294967297.140374069024448
an error occurred:
Wrong version of H5MD file.: iostream error
```
again, so seems related to https://github.com/votca/csg/pull/384

**Comment by junghans** [comment]
On a second thought:
```
Found H5MD version: 4294967297.140374069024448
```
seems just wrong.....

**Comment by junghans** [comment]
@JensWehner, looks uninitialized to me!

**Comment by JensWehner** [comment]
@junghans correct Jens? What do you want me to do?

**Pull request merged**
