### PR TITLE
add iterative integral equation tutorial

### PR DESCRIPTION
**Pull request by marvinbernhardt**
Tutorials related to https://github.com/votca/csg/pull/675

### CODE REVIEW

**Comment by junghans** [comment]
Looking good:
```
Start 207: regression_spce_hncgn
17/36 Test #207: regression_spce_hncgn .......................   Passed   16.93 sec
```

@marvinbernhardt can you run the test locally (`-DENABLE_REGRESSION_TESTING=ON`) and see if it does the right thing?

**Comment by marvinbernhardt** [comment]
Oouh, naphtalene/hncn works, but spce/ihnc and naphtalne/ihnc look off, will check what is going on.

**Comment by junghans** [comment]
Are naphtalene/hncn and  naphtalne/ihnc even in this PR?

**Comment by marvinbernhardt** [comment]
> @marvinbernhardt can you run the test locally (`-DENABLE_REGRESSION_TESTING=ON`) and see if it does the right thing?

Yes, It does the right thing!

**Pull request merged**
