### PR TITLE
Use new Lammps datareader

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by JoshuaSBrown** [comment]
Are you creating an integration test here with the data reader I wrote?

**Comment by junghans** [comment]
Just converting the existing ones!

**Comment by junghans** [comment]
Bug reported as https://github.com/votca/csg/issues/267

**Comment by JoshuaSBrown** [comment]
What was the output of csg-stat before making the switch?

**Comment by junghans** [comment]
It calculated the correct rdf.

**Comment by junghans** [comment]
You can test that with:
```
$ csg_dump --top topol.xml
```

**Pull request merged**
